version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: ptmk_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ptmk_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql_data: